"use client";
import { FormEvent, useRef, useState } from "react";

type Mode="customer_message"|"review_appeal";
export function ReviewsWorkspace(){
  const [mode,setMode]=useState<Mode>("customer_message"),[result,setResult]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState(false);const formRef=useRef<HTMLFormElement>(null);
  async function submit(event?:FormEvent){event?.preventDefault();if(!formRef.current||pending)return;setPending(true);setError("");try{const response=await fetch("/api/reviews/generate",{method:"POST",body:new FormData(formRef.current)}),data=await response.json();if(!response.ok)throw new Error(data.error||"Ошибка сервиса");setResult(data.result);}catch(e){setError(e instanceof Error?e.message:"Не удалось подготовить ответ");}finally{setPending(false);}}
  async function copy(){await navigator.clipboard.writeText(result);}
  return <div className="reviews-workspace"><div className="review-tabs"><button type="button" className={mode==="customer_message"?"active":""} onClick={()=>{setMode("customer_message");setResult("");}}>Сообщения клиентам</button><button type="button" className={mode==="review_appeal"?"active":""} onClick={()=>{setMode("review_appeal");setResult("");}}>Обжалование отзывов</button></div><div className="review-columns"><form ref={formRef} onSubmit={submit} className="card review-form"><input type="hidden" name="type" value={mode}/>{mode==="review_appeal"&&<label>Текст отзыва<textarea name="review" rows={5} maxLength={8000} required placeholder="Вставьте негативный отзыв" /></label>}<label>Опишите ситуацию<textarea name="situation" rows={6} maxLength={8000} required placeholder={mode==="customer_message"?"Что произошло и что нужно сообщить клиенту":"Что произошло с заказом и почему отзыв считаете некорректным"}/></label><label>Текст переписки, если есть<textarea name="conversation" rows={6} maxLength={12000} placeholder="Вставьте переписку без изменений"/></label><label>Скриншоты — до 5 файлов<input name="images" type="file" accept="image/png,image/jpeg,image/webp" multiple/></label><p className="form-hint">PNG, JPEG или WebP; до 4 МБ каждый.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary generate-button" disabled={pending}>{pending?"Готовим ответ...":mode==="customer_message"?"Сгенерировать сообщение":"Подготовить обжалование"}</button></form><section className="card review-result" aria-live="polite"><p className="eyebrow">Результат</p>{result?<><div className="result-text">{result}</div><div className="result-actions"><button type="button" className="primary" onClick={copy}>Скопировать</button><button type="button" className="secondary" disabled={pending} onClick={()=>submit()}>{pending?"Готовим ответ...":"Сгенерировать ещё вариант"}</button></div></>:<p className="period">Здесь появится готовый текст.</p>}</section></div></div>;
}
